services:
  - type: web
    name: django-web
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"